--- Colorschemes ---
require('colorschemes/neosolarized')

--- Plugins Configuration ---
require('configure/autopairs')
require('configure/autotag')
require('configure/battery')
require('configure/bufferline')
require('configure/cmp')
require('configure/code_runner')
require('configure/colorizer')
--require('configure/colortils')
require('configure/comment')
require('configure/hi_my_words')
require('configure/indent_blankline_v3')
require('configure/lsp')
require('configure/lspsaga')
require('configure/lualine')
require('configure/mason')
require('configure/neodev')
require('configure/noice')
require('configure/notify')
require('configure/null_ls')
require('configure/nvim_tree')
require('configure/rainbow')
require('configure/searchbox')
require('configure/sneak')
require('configure/surround')
require('configure/telescope')
require('configure/treesitter')
require('configure/zen_mode')
