require('config-plugins/autopairs')
require('config-plugins/autotag')
require('config-plugins/battery')
require('config-plugins/bufferline')
require('config-plugins/code_runner')
require('config-plugins/colorizer')
require('config-plugins/colortils')
require('config-plugins/hi_my_words')
require('config-plugins/indent_blankline')
require('config-plugins/lualine')
require('config-plugins/nvim_tree')
require('config-plugins/rainbow')
require('config-plugins/searchbox')
require('config-plugins/sneak')
require('config-plugins/surround')
require('config-plugins/telescope')
require('config-plugins/treesitter')
require('config-plugins/zen_mode')
require('config-plugins/cmp_mod')
require('config-plugins/null_ls')
require('config-plugins/lspsaga')
require('config-plugins/comment')
require('config-plugins/mason')
require('config-plugins/lsp')
require('config-plugins/neodev')
--require('config-plugins/noice')


--Colorschemes (Themes)
require('colorschemes/tokyonight')
require('colorschemes/neosolarized')
